Feature/movies info
labotinc/quelcode-team4-2 pull request #26
Opened 2020-11-24 02:32 UTC by MunehiroMachida

## 今回実装した機能、または改善した問題点
映画リスト、映画スケジュールの取り出し。その後座席予約にスケジュールidを送る。

#### 実装の概要
- クリックした時に日付の値をデータベースから取得しページのスケジュールの部分の表示を変えるようにajaxで実装
- 予約購入ボタンを押すと座席予約のページにスケジュールのidを送る。

#### レビューして欲しい内容
- 必要なテーブルが取れているか
└ src/Controller/MoviesInfoController.phpのinitializeでMoviesと、MovieSchedulesの2つのテーブルを取得しているがそれだけでいいのか。
- コード的に遷移先のページに値を送れているか。(予約購入部分)

#### 不安に思っている点
-コードが長すぎないか。読みにくくないか。
- 変数名は適切か。

#### 保留にしている点
-画像が表示されないところ。パスが入るようにはしている。

#### 目標スプリント数、結果スプリント数
- 目標：10
- 結果：20

#### 関連するプルリクあればそのリンク

#### その他
余裕があれば表示チェックもお願いしたいのですがなさそうであれば大丈夫です。
自分のローカルでは表示できています。

2020-11-24 02:53 UTC, Odachannnn commented
レビュー事項一覧
- [ ] アクセスした日を含めて7日を表示する
- [ ] 割引日に該当する日があれば、日付の下に割引名称を表示する
- [ ] 現在アクセスしている日のナビゲーションは黄色にする
- [ ] 押下で押下した日の上映タイトルへページを遷移させる
- [ ] 上記の上映スケジュールナビゲーションで選択されている日付情報
- [ ] 選択されている日付の映画の詳細情報一覧を表示させる。表示項目は次の通り。データベースより検索して表示させる。
 - 映画タイトル
 - 上映時間
- 映画終了予定
- 映画サムネイル画像
- 放映時間（開始時間・終了時間）
- 予約ページ遷移用リンク
 - ※なお、データベースにデータを追加したら、自動的に先の予定の映画も入るような設計にする事
- [ ] 押下で前の画面（画面設計 座席予約を参照）へ遷移する

2020-11-24 07:37 UTC, Odachannnn requested changes
[確認希望]
MovieSchedulesにはないデータが、実際のページに表示されてしまっています。
- 例
<img width="931" alt="スクリーンショット 2020-11-24 16 33 55" src="https://user-images.githubusercontent.com/63225126/100062480-f49cd380-2e72-11eb-94de-e46c8bc67061.png">

実際の画面
<img width="1059" alt="スクリーンショット 2020-11-24 16 34 05" src="https://user-images.githubusercontent.com/63225126/100062502-ff576880-2e72-11eb-8096-b4ef5e2c032d.png">

2020-11-24 07:37 UTC, Odachannnn commented on html/mycakeapp/src/Template/MoviesInfo/index.ctp
> +                        <p class="movie-img"><?php echo $this->Html->image($info->thumbnail_path); ?></p>
[確認希望]
Htmlヘルパーのimageメソッドを使う場合のパスは、
> webroot/img/ と相対的でなければなりません。

とリファレンスにあります。`$info->thumbnail_path`に入っているパスは/var/以降なので、画像が正しく表示されない可能性がありますのでご確認ください。

2020-11-24 07:37 UTC, Odachannnn commented on html/mycakeapp/src/Controller/MoviesInfoController.php
> +        $today = date("Ymd H:i:s");
[提案]
今回必要なのは日付の`Y-m-d`のみなので、`H:i:s`を削ってもいいかなと思います！
それで42行目を削除して、48・49行目に`$today`を使い回すと同じようなコードを減らせるのではないでしょうか？？
```suggestion
        $today = date("Y-m-d");
```

2020-11-24 07:40 UTC, Odachannnn commented on html/mycakeapp/src/Controller/MoviesInfoController.php
> +        $onThatDayMovieSchedules = $this->MovieSchedules->find('all')
`$onThatDayMovieSchedules`が何を指しているのか少しわかりにくいように思います。

変数名から考えるとクリックされたその日のスケジュールを全て取りたいのかと思いますが、
実際のコードを見ると`is_playable = 1`のデータの`id, movie_id, screening_start_datetime`を全て引っ張ってきています。

なので、
- 変数名を変更するか
- where句に `screening_start_datetime LIKE' => 'クリックした日付' .  %`など付け足して変数名にあったクエリを書くか

のどちらかかにした方がいいと思いました。

2020-11-24 13:39 UTC, MunehiroMachida commented on html/mycakeapp/src/Template/MoviesInfo/index.ctp
> +                        <p class="movie-img"><?php echo $this->Html->image($info->thumbnail_path); ?></p>
/img/MovieThumbnails/配下になるようにctpファイル、jsファイルともに修正しました。

2020-11-24 13:42 UTC, MunehiroMachida commented on html/mycakeapp/src/Controller/MoviesInfoController.php
> +        $today = date("Ymd H:i:s");
織田さんのアドバイスをヒントにそもそも変数に入れる工程を消しました！
アドバイスありがとうございます。

2020-11-24 13:53 UTC, MunehiroMachida commented on html/mycakeapp/src/Controller/MoviesInfoController.php
> +        $onThatDayMovieSchedules = $this->MovieSchedules->find('all')
変数名をonThatDayMovieSchedulesからThatDaySchedulesにしました。

この、レビューを見る前に着手していたため
            

>'screening_start_datetime >=' => date("Y-m-d 00:00:00"),
>'screening_start_datetime <=' => date("Y-m-d 23:59:59"),

としました。

2020-11-25 01:30 UTC, Odachannnn commented
- [ ] 画像の表示
- [ ] スケジュールの表示

2020-11-25 01:31 UTC, Odachannnn approved these changes

2020-11-25 01:34 UTC, Odachannnn approved these changes
確認しました！
LGTMです、お疲れ様でした🎉

2020-11-25 01:36 UTC, merged